language: php
php:
  - 5.3
  - 5.4
notifications:
  irc: "irc.freenode.org##atoum"
env:
    global:
        - secure: "W+yK9GdNDif0eKXicjsWToSEDzIcU6T9x156mrJebbaSgVHOUmaIyMWEeJ8d\nI2gY2KhAIcFG7ToQpddbwxJUlCO9yzTJjgsRZj6/I/hOjuq8cDbd04X2aATE\nLCYt0ssEey+zzhHxa0Ka5OVZ/Xj4gc7kQyEifZnlYbgJruBdTQY="
before_script:
  - "[ -n \"$COVERALLS_REPO_TOKEN\" ] && cp resources/configurations/runner/coveralls.php.dist .atoum.php || true"
  - "[ -n \"$COVERALLS_REPO_TOKEN\" ] && sed -i s?/path/to/sources/directory?classes? .atoum.php || true"
  - "[ -n \"$COVERALLS_REPO_TOKEN\" ] && sed -i s/YouCoverallsProjectToken/$COVERALLS_REPO_TOKEN/ .atoum.php || true"
script:
  - php ./scripts/runner.php --test-it